### ISSUE TITLE
Issue with package install through master

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion-saltstack#115]
Had issues when selecting master for package installs during so setup that were not seen when selecting open.

CentOS Storage node install

**Comment by TOoSmOotH** [comment]
so found a couple issues. PIP3 does not work when the sensors or nodes can't talk direct to the internet. This also breaks the docker verify signature stuff. I was able to fix the pip errors by moving to packages on CentOS. This still needs fixed on Ubuntu. I don't have a solution for the registry stuff quite yet.

**Comment by TOoSmOotH** [comment]
Moved Ubuntu back to 2.6. Will address in 18.04. Centos confirmed working. 1.1.3 confirmed and tested
