### ISSUE TITLE
ISO usb install fails to locate kickstart config

### ISSUE THREAD

**Issue by cyberpika2** [Security-Onion-Solutions/securityonion-saltstack#120]
ISO usb install fails to locate kickstart when installing from usb.
Issue related to location of ks.cfg and advanced boot options.
Thank you!

VER:
md5sum HH-1.1.2-2.iso                                                                                                   abbbae7b40a50623546ed3d7f8cda0ec  HH-1.1.2-2.iso

ETC:
ks.cfg location boot command options.
referencing the cdrom for the kickstart errors out during usb installs.

BUG:
ISO installation from USB boot options failure.
Server does not have cdrom, install fails to find kickstart config.

ERROR:
insert cdrom

FIX:
Add boot menu option for install from USB
`vmlinuz initrd=initrd.img inst.ks=hd:LABEL=CentOS\x207\x20x86_64:/ks.cfg inst.stage2=hd:LABEL=CentOS\x207\x20x86_64 quiet`

**Comment by TOoSmOotH** [comment]
This was fixed in 1.1.3
