### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by jrizzie** [Security-Onion-Solutions/securityonion-saltstack#125]
Hello, first post here... so please let me know of any corrections I can make for future posts.  I've been a huge fan of Security Onion, and I think this Hybrid-Hunter project is really awesome.

Is there a specific utility (Win32DiskImager) we should use to write Hybrid-Hunter ISO to a bootable-USB?  I used that and Rufus (using both write options of Rufus) and was not able to get it to install correctly.
*EDIT* - Confirmed the HH1.1-2-2 MD5 matches at source and destination.
*EDIT* - This pertains to installing the ISO as the host operating system, NOT as a VM.

*** The issue I get on installation is:

ERROR:  could not insert 'floppy':  No such device
      Mounting configuration File System...
[OK]  Mounted Configuration File System.
[OK]  Started Show Plymouth Boot Screen.
[OK]  Started Forward Password Requests to Plymouth Directory Watch.
[OK]  Reached target Paths.
[OK]  Reached target Basic System.
[OK]  Started Device-Mapper Multipath Device Controller.
      Starting Open-iSCSI...
[OK]  Started Open-iSCSI.
Starting dracut initqueue hook...
[9.910872] scsi 0:0:0:0: alua: not attached
[9.709859] dracut-initqueue[1341]: mount: /dev/sdb is write-protected, mounting read-only
*this is where it gets hung*

**Comment by cfarquhar** [comment]
I just ran into a similar issue.  The fix for me was to press `tab` at the splash screen and change `ks=cdrom:ks.cfg` to `ks=hd:sdb:/ks.cfg`.  Removing the `quiet` option may also help confirm which block device you should use.

**Comment by TOoSmOotH** [comment]
This should be addresses in 1.1.3. I think there was a mistake on my part on not running a step that makes this work properly with USB. The issue with USB is if you have multiple drives it can sometimes be sdc etc. The KS is actually baked into the initramfs so it will work with either USB or ISO image for a VM or the like.

**Comment by TOoSmOotH** [comment]
1.1.3 confirmed and tested
