### ISSUE TITLE
BPF Solution

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion-saltstack#129]
Replicate the current BPF solution in HH

**Comment by defensivedepth** [comment]
Will need to use this script to gen the required expression - https://github.com/google/stenographer/blob/master/stenotype/compile_bpf.sh

Then add it to `/opt/so/saltstack/salt/pcap/files/config`

For example:

`"--filter=002800000000000c00150008000086dd0030000000000014001502000000008400150100000000060015001100000011002800000000003600150e00000001bb002800000000003800150c0d000001bb0015000c00000800003000000000001700150200000000840015010000000006001500080000001100280000000000140045060000001fff00b100000000000e004800000000000e00150200000001bb004800000000001000150001000001bb00060000000000000006000000040000"`
