### ISSUE TITLE
Enable community id support for Zeek & Suricata

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion-saltstack#210]
Enable Community ID support:

1) Zeek - https://github.com/corelight/bro-community-id#using-the-package

2) Suricata - https://suricata.readthedocs.io/en/suricata-5.0.0/output/eve/eve-json-output.html#community-flow-id

3) add mapping to logstash template

4) Edit Kibana dashboards to allow pivot to Indicators dashboard

**Comment by defensivedepth** [comment]
@TOoSmOotH https://github.com/corelight/bro-community-id
 For Zeek

**Comment by TOoSmOotH** [comment]
This has been pushed. Just needs the Bro scriptage
