### ISSUE TITLE
Prevent any kind of localhost hostname

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion-saltstack#217]
In https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/101, we prevented setting a hostname of `localhost`:
https://github.com/Security-Onion-Solutions/securityonion-saltstack/blob/master/setup/whiptail.sh#L674-L675

However, CentOS 7 installs with a default hostname of `localhost.localdomain`, so we need to expand that check.  Perhaps check to see if $HOSTNAME begins with `localhost` or contains `localhost`?

**Comment by TOoSmOotH** [comment]
https://github.com/Security-Onion-Solutions/securityonion-saltstack/pull/228
