### ISSUE TITLE
include cerebro docker image

### ISSUE THREAD

**Issue by zez3** [Security-Onion-Solutions/securityonion-saltstack#29]
Please include cerebro in the future versions

https://github.com/lmenezes/cerebro
preferably signed by some notary

**Comment by TOoSmOotH** [comment]
ES 7 includes a lot of these features

**Comment by zez3** [comment]
To which features are you referring?
I was reading the release notes and I cannot see the comparable features that you are referring to
https://www.elastic.co/blog/elasticsearch-7-6-0-released#cluster

**Comment by defensivedepth** [comment]
ES7 includes Dev tools, which includes: https://www.elastic.co/guide/en/kibana/current/devtools-kibana.html

What functionality in particular are you looking to have with cerebro?

**Comment by zez3** [comment]
I can monitor my ES cluster state, per node jvm heap size, cpu, memory and disk usage all in a single pane. I can visualize all my index/node distribution and easy 2clicks to move around my shards if needed. I can change cluster settings or templates, etc. most of what can be changed or achieved from an shell but simpler. This was just a suggestion but if it requires a too much effort that I suppose it can be installed by the end user. Last time when I did this I had to change some iptable rules bit on the next soup they where removed together with the image and container.
Anyway. If I remember correctly I eventually modified the soup bash script and added directly there the new docker image and iptables rules.

**Comment by defensivedepth** [comment]
For moving around shards, etc - this is not needed, as we don't use traditional clustering - 

For ES / system monitoring, that will be accomplished through Grafana - 

![image](https://user-images.githubusercontent.com/954732/82681960-80137e80-9c1c-11ea-8b49-4200acee7eb5.png)
