### ISSUE TITLE
Create a "Sample Pcap" docker container with tcpreplay installed

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion-saltstack#32]
Sample PCAPs can be quite large and not everyone needs them in their installs. Create a docker container that can be optional during the install process.

**Comment by weslambert** [comment]
**Intial image**:
https://github.com/Security-Onion-Solutions/securityonion-docker-hh/tree/master/so-tcpreplay
**Initial state**:
https://github.com/Security-Onion-Solutions/securityonion-saltstack/tree/master/salt/tcpreplay

**Comment by weslambert** [comment]
Need to rebuild image and possibly add wrapper script to make replays easier.
