### ISSUE TITLE
Rendering SLS 'firewall.beats_endpoint' failed

### ISSUE THREAD

**Issue by eduardocalfaia** [Security-Onion-Solutions/securityonion-saltstack#341]
Hi Dear,
When I have issued the so-allow command to open the ports I got the error below:local:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'firewall.beats_endpoint' failed. Please see master log for details.
----------
    Rendering SLS 'firewall.osquery_endpoint' failed. Please see master log for details.

Thanks
[ErrorHH.txt](https://github.com/Security-Onion-Solutions/securityonion-saltstack/files/4193534/ErrorHH.txt)

**Comment by TOoSmOotH** [comment]
unacceptable character #x0008: control characters are not allowed

What did you name your sensor?

**Comment by TOoSmOotH** [comment]
I read it closer looks like you have quotes in there. You will need to remove the entry manually from the offending pillars.

**Comment by eduardocalfaia** [comment]
Hi @TOoSmOotH 
The infrastructure is evaluation mode and standalone, I am testing yet using virtualbox and I don't have any sensor.

**Comment by eduardocalfaia** [comment]
I opened the osquery_endpoint.sls and within it, I saw a strange character, for example, 192.16ˆH8.56.0, I canceled that line but I am getting the same error.

**Comment by TOoSmOotH** [comment]
You need to remove it from the beats one as well

**Comment by eduardocalfaia** [comment]
Hi @TOoSmOotH, I did that and it is alright. Thank you
