### ISSUE TITLE
Avoid logstash when possible

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion-saltstack#350]
We can lower total RAM usage in Eval mode by almost 700MB if we can disable logstash altogether and use filebeat to send logs into Elasticsearch.  Zeek logs should already have ES ingest node parsers.  We may need to develop some other ingest node parsers to support non-Zeek data types in Eval mode.

**Comment by weslambert** [comment]
Logstash is no longer used in Eval mode
