### ISSUE TITLE
Add Zeek Scripts

### ISSUE THREAD

**Issue by dondemeier** [Security-Onion-Solutions/securityonion-saltstack#392]
What is the recommended way to add Zeek scripts manually or via zeekpkgs to Security Onion. I tried to follow the "normal" Security Onion docs, but this doesn't work out for Hybrid Hunter.

**Comment by weslambert** [comment]
Users can now specify custom scripts in `/opt/so/saltstack/local/salt/zeek/policy/custom/<scriptdir>`

After adding scripts, they can be added to `load.zeek` by modifying the `/opt/so/saltstack/local/pillar/static.sls` (with `zeek`, `@load` params sourced and modded from `/opt/so/saltstack/default/pillar/zeek/init.sls`) to have it added for the whole grid.
