### ISSUE TITLE
Ubuntu 18.04 Network Manager Errors

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion-saltstack#413]
Getting network manager errors during install when the script goes to modify the interfaces.

**Comment by TOoSmOotH** [comment]
Connection 'bond0' (998be76d-661d-4881-8231-a116c332efc1) successfully added.
Cannot change rx-checksumming
Could not change any device features
Actual changes:
tx-checksumming: off
	tx-checksum-ip-generic: off
tcp-segmentation-offload: off
	tx-tcp-segmentation: off [requested on]
	tx-tcp-ecn-segmentation: off [requested on]
	tx-tcp6-segmentation: off [requested on]
Actual changes:
scatter-gather: off
	tx-scatter-gather: off
generic-segmentation-offload: off [requested on]
Cannot change udp-fragmentation-offload
Cannot change large-receive-offload
Connection 'bond0-slave-ens19' (aa9eee8e-eede-4ebd-b9e0-76c8754f701f) successfully added.
Error: Connection activation failed: No suitable device found for this connection.

Finishing up network setup
... Disabling unused NICs
Error: unknown connection 'ens19'.
... Setting ONBOOT for management interface
Error: unknown connection 'ens18'.
... Copying 00-so-checksum-offload-disable
... Modifying 00-so-checksum-offload-disable
local:

**Comment by rwwiv** [comment]
Error is
```
Connection 'bond0' (998be76d-661d-4881-8231-a116c332efc1) successfully added.
Cannot change rx-checksumming
Could not change any device features
Actual changes:
tx-checksumming: off
	tx-checksum-ip-generic: off
tcp-segmentation-offload: off
	tx-tcp-segmentation: off [requested on]
	tx-tcp-ecn-segmentation: off [requested on]
	tx-tcp6-segmentation: off [requested on]
Actual changes:
scatter-gather: off
	tx-scatter-gather: off
generic-segmentation-offload: off [requested on]
Cannot change udp-fragmentation-offload
Cannot change large-receive-offload
Connection 'bond0-slave-ens19' (aa9eee8e-eede-4ebd-b9e0-76c8754f701f) successfully added.
Error: Connection activation failed: No suitable device found for this connection.
```
and
```
Finishing up network setup
... Disabling unused NICs
Error: unknown connection 'ens19'.
... Setting ONBOOT for management interface
Error: unknown connection 'ens18'.
... Copying 00-so-checksum-offload-disable
... Modifying 00-so-checksum-offload-disable
```
