### ISSUE TITLE
Suricata 5

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion-saltstack#418]
Add Suricata 5 Support

**Comment by dougburks** [comment]
This issue in Suricata 5 is currently targeting 5.0.3:
https://redmine.openinfosecfoundation.org/issues/3342?issue_count=191&issue_position=1&next_issue_id=3341

**Comment by dougburks** [comment]
Suricata 5.0.3 now available!
https://suricata-ids.org/2020/04/28/suricata-5-0-3-released/
