### ISSUE TITLE
Update Fleet to include recent changes

### ISSUE THREAD

**Issue by dlee35** [Security-Onion-Solutions/securityonion-saltstack#47]
The current version is a bit behind Kolide master. We need to merge recent commits, compile, and test in multiple scenarios (e.g. new, upgrade, w/launcher, etc).

**Comment by TOoSmOotH** [comment]
@dlee35 Did this ever go in?

**Comment by TOoSmOotH** [comment]
https://github.com/Security-Onion-Solutions/securityonion-saltstack/pull/60
