### ISSUE TITLE
Move to nmcli bond creation in setup

### ISSUE THREAD

**Issue by rwwiv** [Security-Onion-Solutions/securityonion-saltstack#49]
Current bond creation is distro specific and manipulates files directly. There is a cli tool called nmcli that can create bonds on any distro that uses Network Manager (this includes at a minimum CentOS 7, and Ubuntu 16.04+).

**Comment by TOoSmOotH** [comment]
Tested

**Comment by TOoSmOotH** [comment]
https://github.com/Security-Onion-Solutions/securityonion-saltstack/pull/60
