### ISSUE TITLE
Lock down soremote user on master

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion-saltstack#504]
As a temporary measure soremote user is in the socore group. Ideally this should have reduced access. Yet the remote sensors need to push pillar files up to the master. So consider changing the so-remote script to stop scp'ing into the /opt/so/saltstack/salt directory and instead scp into a soremote writable directory and then have the soremote user ssh into the master and sudo execute a script that has access to copy those pillar files to the secure location. Other options may be possible, this is only one solution.

**Comment by TOoSmOotH** [comment]
Created an add minion script that addresses this concern.
