### ISSUE TITLE
Update 6502 and ossec template

### ISSUE THREAD

**Issue by dlee35** [Security-Onion-Solutions/securityonion-saltstack#58]
Need to update `6502_ossec_autoruns.conf` and `logstash-ossec-template.json` to be at parity with current distro. Additional field was prepended to Autoruns output (Time) and skews parsing.
See: 
https://github.com/Security-Onion-Solutions/security-onion/issues/1535
https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/60

**Comment by TOoSmOotH** [comment]
Ingest
