### ISSUE TITLE
Eval mode so-status reports Logstash as missing

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion-saltstack#582]
Choosing Eval mode and then running `so-status` currently reports Logstash as `MISSING`.  Since Eval mode no longer uses Logstash and instead uses filebeat, we should update `so-status` to reflect that.

![image](https://user-images.githubusercontent.com/1659467/79685339-0e53a980-8206-11ea-889e-b418457a0ec7.png)

**Comment by m0duspwnens** [comment]
resolved with https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/619
