### ISSUE TITLE
Eval mode install fails if you only have 1 interface assigned

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion-saltstack#59]
Need to check if you have more than 1 interface for modes that are sensors.

**Comment by dougburks** [comment]
From Jim Hranicky on mailing list:
```
I forgot to define a second interface in my VM, and when
it got to the screen to select the monitoring interface,
there were no options, and "Ok" and "Cancel" didn't work
and I couldn't leave the screen, even with ctrl-C/ctrl-Z,
etc. I had to kill the installation program from another
virtual console.
```
https://groups.google.com/d/topic/security-onion/FU-UZEhM7-8/discussion

**Comment by m0duspwnens** [comment]
completed: https://github.com/Security-Onion-Solutions/securityonion-saltstack/commit/2d7ff4e0fd3987b8b025219f4da5ba556aca4ab2#diff-51fd25c75ed0288e45b4a74a45eb0364
