### ISSUE TITLE
Zeek Ingest errors

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion-saltstack#594]
Log: https://gist.github.com/defensivedepth/84aca5068028da2c862c3a42e329abad

**Comment by dougburks** [comment]
Perhaps the field check needs the null safe operator (`?.`):
https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-conditional-nullcheck.html

**Comment by TOoSmOotH** [comment]
`[DCE/RPC](/kibana/app/kibana#/dashboard/9e882df0-72c5-11ea-8dd2-9d8795a1200b) |
[DHCP](/kibana/app/kibana#/dashboard/9e882df0-72c5-11ea-8dd2-9d8795a1200b)    `
