### ISSUE TITLE
Sensoroni - gray overlay makes text difficult to read

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion-saltstack#618]
When you hover over a section, the section has a gray overlay, which makes it difficult to read.

![image](https://user-images.githubusercontent.com/954732/80732746-bad13d80-8ada-11ea-8a91-a240818ba558.png)

**Comment by jertel** [comment]
This is no longer an issue due to the color redesign implemented in late May.
