### ISSUE TITLE
cortextscript fails to connect to so-cortex

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion-saltstack#634]
thehive state

If the so-cortex docker isn't already running prior to state run, the thecortexscript state will time out trying to connect.

> ----------
>           ID: so-cortex
>     Function: docker_container.running
>       Result: True
>      Comment: Created container 'so-cortex'
>      Started: 16:04:31.889637
>     Duration: 2901.093 ms
>      Changes:
>               ----------
>               container_id:
>                   ----------
>                   added:
>                       abfe0a9013f05a57e1d0db7ce53643fa7d44b26c49526f16f7e32f096c2b1efd
>               state:
>                   ----------
>                   new:
>                       running
>                   old:
>                       None
> ----------
>           ID: cortexscript
>     Function: cmd.script
>       Result: False
>      Comment: Command 'cortexscript' run
>      Started: 16:04:34.793944
>     Duration: 72588.453 ms
>      Changes:
>               ----------
>               pid:
>                   2353
>               retcode:
>                   1
>               stderr:
>                   * About to connect() to 10.66.166.148 port 443 (#0)
>                   *   Trying 10.66.166.148...
>                     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                                    Dload  Upload   Total   Spent    Left  Speed
> 
>                     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connection refused
>                   * Failed connect to 10.66.166.148:443; Connection refused
>                   * Closing connection 0
>                   curl: (7) Failed connect to 10.66.166.148:443; Connection refused

Same is true for hivescript

> ----------
>           ID: so-thehive
>     Function: docker_container.running
>       Result: True
>      Comment: Created container 'so-thehive'
>      Started: 16:05:47.383108
>     Duration: 2035.589 ms
>      Changes:
>               ----------
>               container_id:
>                   ----------
>                   added:
>                       5055eb1502a632e057d1a98f3283dbd02352fcf89acfbdbc48ef510811d0db5c
>               state:
>                   ----------
>                   new:
>                       running
>                   old:
>                       None
> ----------
>           ID: hivescript
>     Function: cmd.script
>       Result: True
>      Comment: Command 'hivescript' run
>      Started: 16:05:49.419371
>     Duration: 308882.423 ms
>      Changes:
>               ----------
>               pid:
>                   6312
>               retcode:
>                   0
>               stderr:
>               stdout:
>                   Waiting for TheHive....................................................................................................................................................................................................................................................We experienced an issue connecting to TheHive!

**Comment by TOoSmOotH** [comment]
Fixed by starting nginx earlier
