### ISSUE TITLE
Fix DCERPC

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion-saltstack#689]
Need to fix:
- ingest parser
- field mapping
- dashboard and visualizations

**Comment by TOoSmOotH** [comment]
[DCE/RPC](/kibana/app/kibana#/dashboard/9e882df0-72c5-11ea-8dd2-9d8795a1200b) |
[DHCP](/kibana/app/kibana#/dashboard/9e882df0-72c5-11ea-8dd2-9d8795a1200b)

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-saltstack/commit/5d5f5cf105e1330107796f0fb683ee2d63e1d789#diff-8b9aa465ea84277070528c62cc67c990
