### ISSUE TITLE
Hybrid hunter 

### ISSUE THREAD

**Issue by skirankumar** [Security-Onion-Solutions/securityonion-saltstack#71]
can HH run as a stand alone application with out so ? 
if so how to get started on creating playbook.

**Comment by dougburks** [comment]
Hi @skirankumar ,

Hybrid Hunter is simply the code name for the next major version of Security Onion.

To install Hybrid Hunter, please see:
https://blog.securityonion.net/2019/10/security-onion-hybrid-hunter-111-alpha.html

To learn more about Hybrid Hunter, please see:
https://github.com/Security-Onion-Solutions/securityonion-saltstack/wiki

To get started with playbooks, please see:
https://github.com/Security-Onion-Solutions/securityonion-saltstack/wiki/Playbook

If you have further questions about Hybrid Hunter, please post them to https://www.reddit.com/r/securityonion/ and prefix the title with `[Hybrid Hunter]`.

Thanks!
