### ISSUE TITLE
TheHive should use hostname when requested

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion-saltstack#724]
I'm on an Eval install where I chose to connect using hostname instead of IP address.  However, when I login to TheHive and preview an alert, the hyperlinks for Hunt and Kibana are using IP address rather than hostname.

**Comment by dougburks** [comment]
From Josh Brower:

for thehive links its https://github.com/Security-Onion-Solutions/securityonion-saltstack/blob/dev/salt/elastalert/files/rules/so/nids2hive.yaml#L2

**Comment by defensivedepth** [comment]
Need to confirm the same for Fleet

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-saltstack/commit/b951094ea263c2014061d6211298f096dd1aafd5
