### ISSUE TITLE
Incorrect Error message in HH 1.3

### ISSUE THREAD

**Issue by trb143** [Security-Onion-Solutions/securityonion-saltstack#757]
![image](https://user-images.githubusercontent.com/1388819/82691354-ad305300-9c55-11ea-8199-b0584d1e7c8b.png)

**Comment by TOoSmOotH** [comment]
What does the log say?

**Comment by trb143** [comment]
Many issues in the Log due to network problems.  My issue. 
Here you say press Enter but only have an OK.

**Comment by TOoSmOotH** [comment]
If you press the enter as in the return key it will reboot.

**Comment by trb143** [comment]
Yes it did.

**Comment by TOoSmOotH** [comment]
So if it read Select Ok to reboot it would make more sense?

**Comment by trb143** [comment]
Yes it would.

**Comment by TOoSmOotH** [comment]
https://github.com/Security-Onion-Solutions/securityonion-saltstack/commit/d260224dfea4c7b8c384911a452d641d47a432a8
